package com.example.devanswers;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import android.app.Activity;
import android.os.AsyncTask;
import android.os.Bundle;
import android.view.Menu;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.webkit.WebView;
import android.widget.ImageView;
import android.widget.TextView;

public class MainActivity extends Activity {

	ImageView DevMainImage;
	ImageView DevMainImage2;
	WebView Webview;
	MyTask DevMain;
	String note = null;
	
	
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main);
	
		final Animation anim = AnimationUtils.loadAnimation(this, R.anim.shake);
		final TextView NodeText = (TextView)findViewById(R.id.NodeText);
		DevMainImage = (ImageView) findViewById(R.id.DevMainImage);
		DevMainImage2 = (ImageView) findViewById(R.id.DevMainImage2);
		
		OnClickListener onClick = new OnClickListener() {
			public void onClick(View v) {
 
				DevMain = new MyTask();
				DevMain.execute();
				NodeText.setText(note);
				DevMainImage.startAnimation(anim);
					
			}
		};

		DevMainImage2.setOnClickListener(onClick);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	class MyTask extends AsyncTask<Void, Void, Void> {

		@Override
		protected void onPreExecute() {
			super.onPreExecute();			
		}

		@Override
		protected Void doInBackground(Void... params) {
								
			try {				
				
				ArrayList<String> links = new ArrayList<String>();
				links.add("http://devanswers.ru/a/Se");
				links.add("http://devanswers.ru/a/gb");
				links.add("http://devanswers.ru/a/1g");
				links.add("http://devanswers.ru/a/Rh");
				links.add("http://devanswers.ru/a/Dc");
				links.add("http://devanswers.ru/a/Id");
				links.add("http://devanswers.ru/a/Tb");
				links.add("http://devanswers.ru/a/yg");
				links.add("http://devanswers.ru/a/sj");
				links.add("http://devanswers.ru/a/pg");
				links.add("http://devanswers.ru/a/kh");
				links.add("http://devanswers.ru/a/rg");
				links.add("http://devanswers.ru/a/rf");
				links.add("http://devanswers.ru/a/Bd");
				links.add("http://devanswers.ru/a/1j");
				links.add("http://devanswers.ru/a/Li");
				links.add("http://devanswers.ru/a/bd");
				links.add("http://devanswers.ru/a/Xi");
				links.add("http://devanswers.ru/a/2j");
				links.add("http://devanswers.ru/a/6f");
				links.add("http://devanswers.ru/a/Eb");
				links.add("http://devanswers.ru/a/Lg");
				links.add("http://devanswers.ru/a/4b");
				links.add("http://devanswers.ru/a/gf");
				links.add("http://devanswers.ru/a/zb");
				links.add("http://devanswers.ru/a/Hb");
				links.add("http://devanswers.ru/a/jh");
				links.add("http://devanswers.ru/a/Ah");
				links.add("http://devanswers.ru/a/wh");
				links.add("http://devanswers.ru/a/Lc");
				links.add("http://devanswers.ru/a/xe");
				links.add("http://devanswers.ru/a/Hi");
				links.add("http://devanswers.ru/a/Fh");
				links.add("http://devanswers.ru/a/Ic");
				links.add("http://devanswers.ru/a/ii");
				links.add("http://devanswers.ru/a/Wb");
				links.add("http://devanswers.ru/a/Ad");
				links.add("http://devanswers.ru/a/kc");
				links.add("http://devanswers.ru/a/Rd");
				links.add("http://devanswers.ru/a/Zc");
				links.add("http://devanswers.ru/a/Wi");
				links.add("http://devanswers.ru/a/Bg");
				links.add("http://devanswers.ru/a/ge");
				links.add("http://devanswers.ru/a/zj");
				links.add("http://devanswers.ru/a/pe");
				links.add("http://devanswers.ru/a/Ji");
				links.add("http://devanswers.ru/a/Bh");
				links.add("http://devanswers.ru/a/Kc");
				links.add("http://devanswers.ru/a/qj");
				links.add("http://devanswers.ru/a/xd");
				links.add("http://devanswers.ru/a/ub");
				links.add("http://devanswers.ru/a/Ee");
				links.add("http://devanswers.ru/a/gd");
				links.add("http://devanswers.ru/a/rc");
				links.add("http://devanswers.ru/a/Cb");
				links.add("http://devanswers.ru/a/fh");
				links.add("http://devanswers.ru/a/lf");
				links.add("http://devanswers.ru/a/0b");
				links.add("http://devanswers.ru/a/gg");
				links.add("http://devanswers.ru/a/Wg");
				links.add("http://devanswers.ru/a/yf");
				links.add("http://devanswers.ru/a/0h");
				links.add("http://devanswers.ru/a/Bi");
				links.add("http://devanswers.ru/a/li");
				links.add("http://devanswers.ru/a/ei");
				links.add("http://devanswers.ru/a/bj");
				links.add("http://devanswers.ru/a/hj");
				links.add("http://devanswers.ru/a/ki");
				links.add("http://devanswers.ru/a/Gf");
				links.add("http://devanswers.ru/a/tg");
				links.add("http://devanswers.ru/a/Sg");
				links.add("http://devanswers.ru/a/nd");
				links.add("http://devanswers.ru/a/1f");
				links.add("http://devanswers.ru/a/He");
				links.add("http://devanswers.ru/a/Ib");
				links.add("http://devanswers.ru/a/re");
				links.add("http://devanswers.ru/a/ah");
				links.add("http://devanswers.ru/a/Td");
				links.add("http://devanswers.ru/a/sc");
				links.add("http://devanswers.ru/a/7f");
				links.add("http://devanswers.ru/a/Rf");
				links.add("http://devanswers.ru/a/Jh");
				links.add("http://devanswers.ru/a/Vd");
				links.add("http://devanswers.ru/a/tc");
				links.add("http://devanswers.ru/a/Fi");
				links.add("http://devanswers.ru/a/ee");
				links.add("http://devanswers.ru/a/he");
				links.add("http://devanswers.ru/a/uf");
				links.add("http://devanswers.ru/a/Hd");
				links.add("http://devanswers.ru/a/9b");
				links.add("http://devanswers.ru/a/hg");
				links.add("http://devanswers.ru/a/eb");
				links.add("http://devanswers.ru/a/oc");
				links.add("http://devanswers.ru/a/Ed");
				links.add("http://devanswers.ru/a/0c");
				links.add("http://devanswers.ru/a/ce");
				links.add("http://devanswers.ru/a/ej");
				links.add("http://devanswers.ru/a/Hg");
				links.add("http://devanswers.ru/a/Jd");
				links.add("http://devanswers.ru/a/cg");
				links.add("http://devanswers.ru/a/xb");
				links.add("http://devanswers.ru/a/Pd");
				links.add("http://devanswers.ru/a/Jf");
				links.add("http://devanswers.ru/a/Je");
				links.add("http://devanswers.ru/a/5h");
				links.add("http://devanswers.ru/a/wi");
				links.add("http://devanswers.ru/a/Nf");
				links.add("http://devanswers.ru/a/Xg");
				links.add("http://devanswers.ru/a/sb");
				links.add("http://devanswers.ru/a/fi");
				links.add("http://devanswers.ru/a/0d");
				links.add("http://devanswers.ru/a/de");
				links.add("http://devanswers.ru/a/Ki");
				links.add("http://devanswers.ru/a/5e");
				links.add("http://devanswers.ru/a/Wc");
				links.add("http://devanswers.ru/a/2d");
				links.add("http://devanswers.ru/a/Fd");
				links.add("http://devanswers.ru/a/md");
				links.add("http://devanswers.ru/a/jc");
				links.add("http://devanswers.ru/a/4c");
				links.add("http://devanswers.ru/a/Zf");
				links.add("http://devanswers.ru/a/tb");
				links.add("http://devanswers.ru/a/wj");
				links.add("http://devanswers.ru/a/kj");
				links.add("http://devanswers.ru/a/De");
				links.add("http://devanswers.ru/a/mi");
				links.add("http://devanswers.ru/a/4e");
				links.add("http://devanswers.ru/a/Md");
				links.add("http://devanswers.ru/a/gj");
				links.add("http://devanswers.ru/a/mh");
				links.add("http://devanswers.ru/a/2g");
				links.add("http://devanswers.ru/a/sf");
				links.add("http://devanswers.ru/a/Db");
				links.add("http://devanswers.ru/a/4d");
				links.add("http://devanswers.ru/a/zi");
				links.add("http://devanswers.ru/a/oe");
				links.add("http://devanswers.ru/a/zh");
				links.add("http://devanswers.ru/a/Hh");
				links.add("http://devanswers.ru/a/Ph");
				links.add("http://devanswers.ru/a/2i");
				links.add("http://devanswers.ru/a/Ug");
				links.add("http://devanswers.ru/a/0i");
				links.add("http://devanswers.ru/a/Ec");
				links.add("http://devanswers.ru/a/fd");
				links.add("http://devanswers.ru/a/sh");
				links.add("http://devanswers.ru/a/bb");
				links.add("http://devanswers.ru/a/Ne");
				links.add("http://devanswers.ru/a/di");
				links.add("http://devanswers.ru/a/Me");
				links.add("http://devanswers.ru/a/Oh");
				links.add("http://devanswers.ru/a/le");
				links.add("http://devanswers.ru/a/Qh");
				links.add("http://devanswers.ru/a/Fb");
				links.add("http://devanswers.ru/a/kb");
				links.add("http://devanswers.ru/a/Mc");
				links.add("http://devanswers.ru/a/Pe");
				links.add("http://devanswers.ru/a/ec");
				links.add("http://devanswers.ru/a/id");
				links.add("http://devanswers.ru/a/Le");
				links.add("http://devanswers.ru/a/Qf");
				links.add("http://devanswers.ru/a/cb");
				links.add("http://devanswers.ru/a/lg");
				links.add("http://devanswers.ru/a/rd");
				links.add("http://devanswers.ru/a/lj");
				links.add("http://devanswers.ru/a/Cf");
				links.add("http://devanswers.ru/a/td");
				links.add("http://devanswers.ru/a/5g");
				links.add("http://devanswers.ru/a/qh");
				links.add("http://devanswers.ru/a/2f");
				links.add("http://devanswers.ru/a/jj");
				links.add("http://devanswers.ru/a/fj");
				links.add("http://devanswers.ru/a/Xf");
				links.add("http://devanswers.ru/a/ff");
				links.add("http://devanswers.ru/a/ph");
				links.add("http://devanswers.ru/a/Od");
				links.add("http://devanswers.ru/a/fe");
				links.add("http://devanswers.ru/a/Zh");
				links.add("http://devanswers.ru/a/Kf");
				links.add("http://devanswers.ru/a/jg");
				links.add("http://devanswers.ru/a/Og");
				links.add("http://devanswers.ru/a/Ab");
				links.add("http://devanswers.ru/a/yj");
				links.add("http://devanswers.ru/a/te");
				links.add("http://devanswers.ru/a/6i");
				links.add("http://devanswers.ru/a/Ui");
				links.add("http://devanswers.ru/a/rb");
				links.add("http://devanswers.ru/a/vf");
				links.add("http://devanswers.ru/a/je");
				links.add("http://devanswers.ru/a/Oc");
				links.add("http://devanswers.ru/a/8e");
				links.add("http://devanswers.ru/a/Zd");
				links.add("http://devanswers.ru/a/Rg");
				links.add("http://devanswers.ru/a/eg");
				links.add("http://devanswers.ru/a/Gg");
				links.add("http://devanswers.ru/a/ie");
				links.add("http://devanswers.ru/a/nj");
				links.add("http://devanswers.ru/a/Af");
				links.add("http://devanswers.ru/a/ve");
				links.add("http://devanswers.ru/a/Mb");
				links.add("http://devanswers.ru/a/mj");
				links.add("http://devanswers.ru/a/Dd");
				links.add("http://devanswers.ru/a/ug");
				links.add("http://devanswers.ru/a/Gi");
				links.add("http://devanswers.ru/a/ri");
				links.add("http://devanswers.ru/a/Qe");
				links.add("http://devanswers.ru/a/Ni");
				links.add("http://devanswers.ru/a/xh");
				links.add("http://devanswers.ru/a/6h");
				links.add("http://devanswers.ru/a/zc");
				links.add("http://devanswers.ru/a/Nd");
				links.add("http://devanswers.ru/a/Gb");
				links.add("http://devanswers.ru/a/Of");
				links.add("http://devanswers.ru/a/Ih");
				links.add("http://devanswers.ru/a/Lh");
				links.add("http://devanswers.ru/a/Ri");
				links.add("http://devanswers.ru/a/dc");
				links.add("http://devanswers.ru/a/Gd");
				links.add("http://devanswers.ru/a/we");
				links.add("http://devanswers.ru/a/pf");
				links.add("http://devanswers.ru/a/zf");
				links.add("http://devanswers.ru/a/ad");
				links.add("http://devanswers.ru/a/Mf");
				links.add("http://devanswers.ru/a/Xd");
				links.add("http://devanswers.ru/a/ue");
				links.add("http://devanswers.ru/a/pi");
				links.add("http://devanswers.ru/a/Sc");
				links.add("http://devanswers.ru/a/8d");
				links.add("http://devanswers.ru/a/db");
				links.add("http://devanswers.ru/a/xj");
				links.add("http://devanswers.ru/a/Yd");
				links.add("http://devanswers.ru/a/Ye");
				links.add("http://devanswers.ru/a/Uf");
				links.add("http://devanswers.ru/a/3e");
				links.add("http://devanswers.ru/a/sd");
				links.add("http://devanswers.ru/a/tf");
				links.add("http://devanswers.ru/a/Ng");
				links.add("http://devanswers.ru/a/Rc");
				links.add("http://devanswers.ru/a/dj");
				links.add("http://devanswers.ru/a/Gc");
				links.add("http://devanswers.ru/a/nf");
				links.add("http://devanswers.ru/a/Mi");
				links.add("http://devanswers.ru/a/bc");
				links.add("http://devanswers.ru/a/4g");
				links.add("http://devanswers.ru/a/7d");
				links.add("http://devanswers.ru/a/bh");
				links.add("http://devanswers.ru/a/Tc");
				links.add("http://devanswers.ru/a/gc");
				links.add("http://devanswers.ru/a/7b");
				links.add("http://devanswers.ru/a/2c");
				links.add("http://devanswers.ru/a/hc");
				links.add("http://devanswers.ru/a/ui");
				links.add("http://devanswers.ru/a/Ue");
				links.add("http://devanswers.ru/a/Mh");
				links.add("http://devanswers.ru/a/gh");
				links.add("http://devanswers.ru/a/ef");
				links.add("http://devanswers.ru/a/Hf");
				links.add("http://devanswers.ru/a/hi");
				links.add("http://devanswers.ru/a/Wf");
				links.add("http://devanswers.ru/a/Wh");
				links.add("http://devanswers.ru/a/1c");
				links.add("http://devanswers.ru/a/ch");
				links.add("http://devanswers.ru/a/qi");
				links.add("http://devanswers.ru/a/pd");
				links.add("http://devanswers.ru/a/Sb");
				links.add("http://devanswers.ru/a/Xh");
				links.add("http://devanswers.ru/a/mg");
				links.add("http://devanswers.ru/a/Qi");
				links.add("http://devanswers.ru/a/pj");
				links.add("http://devanswers.ru/a/Te");
				links.add("http://devanswers.ru/a/ng");
				links.add("http://devanswers.ru/a/vh");
				links.add("http://devanswers.ru/a/cj");
				links.add("http://devanswers.ru/a/yb");
				links.add("http://devanswers.ru/a/Ce");
				links.add("http://devanswers.ru/a/7g");
				links.add("http://devanswers.ru/a/Re");
				links.add("http://devanswers.ru/a/Of");
				links.add("http://devanswers.ru/a/pi");
				links.add("http://devanswers.ru/a/db");
				links.add("http://devanswers.ru/a/nf");
				links.add("http://devanswers.ru/a/ef");
				links.add("http://devanswers.ru/a/Te");
				links.add("http://devanswers.ru/a/vh");
				links.add("http://devanswers.ru/a/ld");
				links.add("http://devanswers.ru/a/yb");
				links.add("http://devanswers.ru/a/Xc");
				links.add("http://devanswers.ru/a/xg");
				links.add("http://devanswers.ru/a/Ce");
				links.add("http://devanswers.ru/a/tj");
				links.add("http://devanswers.ru/a/Ke");
				links.add("http://devanswers.ru/a/Re");
				links.add("http://devanswers.ru/a/wb");
				links.add("http://devanswers.ru/a/Be");
				links.add("http://devanswers.ru/a/3f");
				links.add("http://devanswers.ru/a/3d");
				links.add("http://devanswers.ru/a/Lf");
				links.add("http://devanswers.ru/a/Ge");
				links.add("http://devanswers.ru/a/wc");
				links.add("http://devanswers.ru/a/jd");
				links.add("http://devanswers.ru/a/Ai");
				links.add("http://devanswers.ru/a/ne");
				links.add("http://devanswers.ru/a/Pc");
				links.add("http://devanswers.ru/a/gi");
				links.add("http://devanswers.ru/a/qg");
				links.add("http://devanswers.ru/a/kd");
				links.add("http://devanswers.ru/a/Bf");
				links.add("http://devanswers.ru/a/Dh");
				links.add("http://devanswers.ru/a/ig");
				links.add("http://devanswers.ru/a/8f");
				links.add("http://devanswers.ru/a/Ob");
				links.add("http://devanswers.ru/a/cf");
				links.add("http://devanswers.ru/a/Ch");
				links.add("http://devanswers.ru/a/Uc");
				links.add("http://devanswers.ru/a/Sf");
				links.add("http://devanswers.ru/a/Kg");
				links.add("http://devanswers.ru/a/Fc");
				links.add("http://devanswers.ru/a/yc");
				links.add("http://devanswers.ru/a/Cg");
				links.add("http://devanswers.ru/a/9i");
				links.add("http://devanswers.ru/a/lb");
				links.add("http://devanswers.ru/a/Rb");
				links.add("http://devanswers.ru/a/df");
				links.add("http://devanswers.ru/a/Sh");
				links.add("http://devanswers.ru/a/Pb");
				links.add("http://devanswers.ru/a/Qg");
				links.add("http://devanswers.ru/a/5c");
				links.add("http://devanswers.ru/a/8b");
				links.add("http://devanswers.ru/a/6b");
				links.add("http://devanswers.ru/a/nb");
				links.add("http://devanswers.ru/a/og");
				links.add("http://devanswers.ru/a/Si");
				links.add("http://devanswers.ru/a/hd");
				links.add("http://devanswers.ru/a/5b");
				links.add("http://devanswers.ru/a/af");
				links.add("http://devanswers.ru/a/wf");
				links.add("http://devanswers.ru/a/fc");
				links.add("http://devanswers.ru/a/zg");
				links.add("http://devanswers.ru/a/8c");
				links.add("http://devanswers.ru/a/qb");
				links.add("http://devanswers.ru/a/vg");
				links.add("http://devanswers.ru/a/Ac");
				links.add("http://devanswers.ru/a/8h");
				links.add("http://devanswers.ru/a/bg");
				links.add("http://devanswers.ru/a/3i");
				links.add("http://devanswers.ru/a/Cd");
				links.add("http://devanswers.ru/a/Ib");
				links.add("http://devanswers.ru/a/be");
				links.add("http://devanswers.ru/a/Tf");
				links.add("http://devanswers.ru/a/1b");
				links.add("http://devanswers.ru/a/Ud");
				links.add("http://devanswers.ru/a/xf");
				links.add("http://devanswers.ru/a/ib");
				links.add("http://devanswers.ru/a/ye");
				links.add("http://devanswers.ru/a/wg");
				links.add("http://devanswers.ru/a/Th");
				links.add("http://devanswers.ru/a/9h");
				links.add("http://devanswers.ru/a/nh");
				links.add("http://devanswers.ru/a/uh");
				links.add("http://devanswers.ru/a/Ei");
				links.add("http://devanswers.ru/a/Eg");
				links.add("http://devanswers.ru/a/qc");
				links.add("http://devanswers.ru/a/vb");
				links.add("http://devanswers.ru/a/Vc");
				links.add("http://devanswers.ru/a/hh");
				links.add("http://devanswers.ru/a/vc");
				links.add("http://devanswers.ru/a/4h");
				links.add("http://devanswers.ru/a/zd");
				links.add("http://devanswers.ru/a/Vg");
				links.add("http://devanswers.ru/a/0e");
				links.add("http://devanswers.ru/a/ae");
				links.add("http://devanswers.ru/a/If");
				links.add("http://devanswers.ru/a/Ie");
				links.add("http://devanswers.ru/a/qf");
				links.add("http://devanswers.ru/a/Yf");
				links.add("http://devanswers.ru/a/pb");
				links.add("http://devanswers.ru/a/ci");
				links.add("http://devanswers.ru/a/Yc");
				links.add("http://devanswers.ru/a/dh");
				links.add("http://devanswers.ru/a/ij");
				links.add("http://devanswers.ru/a/Kb");
				links.add("http://devanswers.ru/a/ag");
				links.add("http://devanswers.ru/a/rj");
				links.add("http://devanswers.ru/a/ze");
				links.add("http://devanswers.ru/a/Ig");
				links.add("http://devanswers.ru/a/0j");
				links.add("http://devanswers.ru/a/Qc");
				links.add("http://devanswers.ru/a/5f");
				links.add("http://devanswers.ru/a/vi");
				links.add("http://devanswers.ru/a/kg");
				links.add("http://devanswers.ru/a/Lb");
				links.add("http://devanswers.ru/a/rh");
				links.add("http://devanswers.ru/a/fg");
				links.add("http://devanswers.ru/a/5i");
				links.add("http://devanswers.ru/a/bf");
				links.add("http://devanswers.ru/a/bi");
				links.add("http://devanswers.ru/a/Ii");
				links.add("http://devanswers.ru/a/Vi");
				links.add("http://devanswers.ru/a/2h");
				links.add("http://devanswers.ru/a/4f");
				links.add("http://devanswers.ru/a/We");
				links.add("http://devanswers.ru/a/Bb");
				links.add("http://devanswers.ru/a/mf");
				links.add("http://devanswers.ru/a/Eh");
				links.add("http://devanswers.ru/a/9g");
				links.add("http://devanswers.ru/a/Bc");
				links.add("http://devanswers.ru/a/Qd");
				links.add("http://devanswers.ru/a/Ti");
				links.add("http://devanswers.ru/a/Dg");
				links.add("http://devanswers.ru/a/Qb");
				links.add("http://devanswers.ru/a/1e");
				links.add("http://devanswers.ru/a/ai");
				links.add("http://devanswers.ru/a/lc");
				links.add("http://devanswers.ru/a/7h");
				links.add("http://devanswers.ru/a/uj");
				links.add("http://devanswers.ru/a/hf");
				links.add("http://devanswers.ru/a/3h");
				links.add("http://devanswers.ru/a/Nb");
				links.add("http://devanswers.ru/a/5d");
				links.add("http://devanswers.ru/a/Ae");
				links.add("http://devanswers.ru/a/xi");
				links.add("http://devanswers.ru/a/Ld");
				links.add("http://devanswers.ru/a/Jc");
				links.add("http://devanswers.ru/a/Vf");
				links.add("http://devanswers.ru/a/od");
				links.add("http://devanswers.ru/a/Mg");
				links.add("http://devanswers.ru/a/8i");
				links.add("http://devanswers.ru/a/Pf");
				links.add("http://devanswers.ru/a/nc");
				links.add("http://devanswers.ru/a/Yi");
				links.add("http://devanswers.ru/a/mc");
				links.add("http://devanswers.ru/a/Oe");
				links.add("http://devanswers.ru/a/Yb");
				links.add("http://devanswers.ru/a/th");
				links.add("http://devanswers.ru/a/me");
				links.add("http://devanswers.ru/a/oi");
				links.add("http://devanswers.ru/a/Uh");
				links.add("http://devanswers.ru/a/jf");
				links.add("http://devanswers.ru/a/dg");
				links.add("http://devanswers.ru/a/sg");
				links.add("http://devanswers.ru/a/xc");
				
				Random rand = new Random();
				int number = rand.nextInt(440);
				
				Document doc = null;
	            doc = Jsoup.connect((String) links.get(number)).get();
	            Elements element = doc.select("h1 > a > span");
	            note = element.tagName("span").text();      
	            
	        } catch (IOException e) {
	            e.printStackTrace();
	        }
			
			return null;
				
		}

		@Override
		protected void onPostExecute(Void result) {
			super.onPostExecute(result);
		}
	}

}
