package com.example.devanswers;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Color;
import android.net.ConnectivityManager;
import android.os.AsyncTask;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.ShareActionProvider;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends Activity  {

	ImageView DevMainImage;
	ImageView DevMainImage2;
	TextView LinkID;
	MyTask DevMain;
	String note;
	final List<String> colors = new ArrayList<String>();
	final ArrayList<String> links = new ArrayList<String>();
	int number = 0;
	Elements element;
	MenuItem shareItem;
	ProgressDialog ProgressDialog;
	private boolean parsingSuccessful = true;
	TextView NodeText;
	
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main);
			
		final Animation anim = AnimationUtils.loadAnimation(this, R.anim.shake);
		NodeText = (TextView)findViewById(R.id.NodeText);
		
		DevMainImage = (ImageView) findViewById(R.id.DevMainImage);
		DevMainImage2 = (ImageView) findViewById(R.id.DevMainImage2);

		OnClickListener onClick = new OnClickListener() {
			public void onClick(View v) {
				
				if (isOnline() == false) {

					Toast toast = Toast.makeText(getApplicationContext(),
							R.string.connection, Toast.LENGTH_SHORT);
					toast.show();
				}
				
				else {
												
					DevMainImage.startAnimation(anim);
					DevMain = new MyTask();
					DevMain.execute();	
					
				}
				
			}
		};

		DevMainImage2.setOnClickListener(onClick);
	}
		
	public void colors() {
	
		//385 757 544 650 325 690 510 305 304 362 109 449 531
		
				colors.add("#5D8AA8");
				colors.add("#64E986");
				colors.add("#F0F8FF");
				colors.add("#6CC417");
				colors.add("#FFBF00");
				colors.add("#FF033E");
				colors.add("#9966CC");
				colors.add("#A4C639");
				colors.add("#CD9575");
				colors.add("#915C83");
				colors.add("#7FFFD4");
				colors.add("#827B60");
				colors.add("#4B5320");
				colors.add("#B2BEB5");
				colors.add("#87A96B");
				colors.add("#FDEE00");
				colors.add("#6E7F80");
				colors.add("#B2C248");
				colors.add("#FF2052");
				colors.add("#893BFF");
				colors.add("#007FFF");
				colors.add("#89CFF0");
				colors.add("#A1CAF1");
				colors.add("#21ABCD");
				colors.add("#FFE135");
				colors.add("#C25283");
				colors.add("#F88158");
				colors.add("#848482");
				colors.add("#98777B");
				colors.add("#F75D59");
				colors.add("#9F8170");
				colors.add("#E9AB17");
				colors.add("#FBB117");
				colors.add("#4C787E");
				colors.add("#3D2B1F");
				colors.add("#FE6F5E");
				colors.add("#413839");
				colors.add("#4C4646");
				colors.add("#463E3F");
				colors.add("#318CE7");
				colors.add("#ACE5EE");
				colors.add("#7E3517");
				colors.add("#F9B7FF");
				colors.add("#B7CEEC");
				colors.add("#A2A2D0");
				colors.add("#4EE2EC");
				colors.add("#157DEC");
				colors.add("#1569C7");
				colors.add("#98AFC7");
				colors.add("#0D98BA");
				colors.add("#77BFC7");
				colors.add("#3090C7");
				colors.add("#2B547E");
				colors.add("#659EC7");
				colors.add("#8EEBEC");
				colors.add("#6960EC");
				colors.add("#1F45FC");
				colors.add("#8A2BE2");
				colors.add("#306EFF");
				colors.add("#342D7E");
				colors.add("#57FEFF");
				colors.add("#0041C2");
				colors.add("#DE5D83");
				colors.add("#E6A9EC");
				colors.add("#E56E94");
				colors.add("#79443B");
				colors.add("#0095B6");
				colors.add("#E3DAC9");
				colors.add("#006A4E");
				colors.add("#873260");
				colors.add("#0070FF");
				colors.add("#B5A642");
				colors.add("#CB4154");
				colors.add("#FDD017");
				colors.add("#66FF00");
				colors.add("#BF94E4");
				colors.add("#C32148");
				colors.add("#F433FF");
				colors.add("#FF007F");
				colors.add("#08E8DE");
				colors.add("#D19FE8");
				colors.add("#FF55A3");
				colors.add("#FB607F");
				colors.add("#004225");
				colors.add("#CD7F32");
				colors.add("#835C3B");
				colors.add("#E2A76F");
				colors.add("#F0DC82");
				colors.add("#480607");
				colors.add("#8C001A");
				colors.add("#DEB887");
				colors.add("#CC5500");
				colors.add("#C12267");
				colors.add("#E97451");
				colors.add("#8A3324");
				colors.add("#38ACEC");
				colors.add("#BD33A4");
				colors.add("#702963");
				colors.add("#536872");
				colors.add("#5F9EA0");
				colors.add("#91A3B0");
				colors.add("#E38AAE");
				colors.add("#006B3C");
				colors.add("#ED872D");
				colors.add("#FFF600");
				colors.add("#4B3621");
				colors.add("#1E4D2B");
				colors.add("#A3C1AD");
				colors.add("#C19A6B");
				colors.add("#FFEF00");
				colors.add("#FF0800");
				colors.add("#E4717A");
				colors.add("#FFA62F");
				colors.add("#00BFFF");
				colors.add("#592720");
				colors.add("#C68E17");
				colors.add("#625D5D");
				colors.add("#C41E3A");
				colors.add("#00CC99");
				colors.add("#FF0040");
				colors.add("#EB4C42");
				colors.add("#FF0038");
				colors.add("#C12283");
				colors.add("#FFA6C9");
				colors.add("#F778A1");
				colors.add("#99BADD");
				colors.add("#ED9121");
				colors.add("#ACE1AF");
				colors.add("#B2FFFF");
				colors.add("#4997D0");
				colors.add("#EC3B83");
				colors.add("#007BA7");
				colors.add("#2A52BE");
				colors.add("#007AA5");
				colors.add("#E03C31");
				colors.add("#A0785A");
				colors.add("#FAD6A5");
				colors.add("#34282C");
				colors.add("#7FFF00");
				colors.add("#8AFB17");
				colors.add("#DE3163");
				colors.add("#FFB7C5");
				colors.add("#C24641");
				colors.add("#CD5C5C");
				colors.add("#C34A2C");
				colors.add("#C11B17");
				colors.add("#D2691E");
				colors.add("#FFA700");
				colors.add("#98817B");
				colors.add("#E34234");
				colors.add("#E4D00A");
				colors.add("#6D6968");
				colors.add("#3EA055");
				colors.add("#0047AB");
				colors.add("#0020C2");
				colors.add("#6F4E37");
				colors.add("#9BDDFF");
				colors.add("#F87431");
				colors.add("#C7A317");
				colors.add("#002E63");
				colors.add("#8C92AC");
				colors.add("#B87333");
				colors.add("#996666");
				colors.add("#FF3800");
				colors.add("#FF7F50");
				colors.add("#AFDCEC");
				colors.add("#F88379");
				colors.add("#FF4040");
				colors.add("#893F45");
				colors.add("#FFF380");
				colors.add("#B31B1B");
				colors.add("#9ACEEB");
				colors.add("#6495ED");
				colors.add("#FCDFFF");
				colors.add("#9F000F");
				colors.add("#DC143C");
				colors.add("#BE0032");
				colors.add("#990000");
				colors.add("#9172EC");
				colors.add("#00FFFF");
				colors.add("#FFFF31");
				colors.add("#F0E130");
				colors.add("#00008B");
				colors.add("#654321");
				colors.add("#5D3954");
				colors.add("#A40000");
				colors.add("#08457E");
				colors.add("#986960");
				colors.add("#CD5B45");
				colors.add("#008B8B");
				colors.add("#536878");
				colors.add("#254117");
				colors.add("#AF7817");
				colors.add("#B8860B");
				colors.add("#A9A9A9");
				colors.add("#013220");
				colors.add("#1A2421");
				colors.add("#BDB76B");
				colors.add("#734F96");
				colors.add("#8B008B");
				colors.add("#003366");
				colors.add("#556B2F");
				colors.add("#FF8C00");
				colors.add("#9932CC");
				colors.add("#779ECB");
				colors.add("#03C03C");
				colors.add("#966FD6");
				colors.add("#C23B22");
				colors.add("#E75480");
				colors.add("#003399");
				colors.add("#872657");
				colors.add("#8B0000");
				colors.add("#E18B6B");
				colors.add("#E9967A");
				colors.add("#560319");
				colors.add("#8BB381");
				colors.add("#8FBC8F");
				colors.add("#3C1414");
				colors.add("#2B3856");
				colors.add("#483D8B");
				colors.add("#25383C");
				colors.add("#2F4F4F");
				colors.add("#177245");
				colors.add("#918151");
				colors.add("#FFA812");
				colors.add("#CC4E5C");
				colors.add("#00CED1");
				colors.add("#3B9C9C");
				colors.add("#842DCE");
				colors.add("#9400D3");
				colors.add("#00693E");
				colors.add("#555555");
				colors.add("#D70A53");
				colors.add("#A9203E");
				colors.add("#EF3038");
				colors.add("#E9692C");
				colors.add("#FAD6A5");
				colors.add("#B94E48");
				colors.add("#704241");
				colors.add("#C154C1");
				colors.add("#004B49");
				colors.add("#9955BB");
				colors.add("#FFCBA4");
				colors.add("#FF1493");
				colors.add("#FF9933");
				colors.add("#3BB9FF");
				colors.add("#1560BD");
				colors.add("#79BAEC");
				colors.add("#EDC9AF");
				colors.add("#696969");
				colors.add("#E3319D");
				colors.add("#1E90FF");
				colors.add("#D71868");
				colors.add("#6AFB92");
				colors.add("#00009C");
				colors.add("#7F525D");
				colors.add("#0000A0");
				colors.add("#E1A95F");
				colors.add("#9AFEFF");
				colors.add("#00FF00");
				colors.add("#F4BBFF");
				colors.add("#BF00FF");
				colors.add("#3F00FF");
				colors.add("#8F00FF");
				colors.add("#50C878");
				colors.add("#5FFB17");
				colors.add("#96C8A2");
				colors.add("#C8B560");
				colors.add("#801818");
				colors.add("#FF00FF");
				colors.add("#B53389");
				colors.add("#F400A1");
				colors.add("#E5AA70");
				colors.add("#4D5D53");
				colors.add("#71BC78");
				colors.add("#667C26");
				colors.add("#F70D1A");
				colors.add("#6C541E");
				colors.add("#CE2029");
				colors.add("#B22222");
				colors.add("#E25822");
				colors.add("#FC8EAC");
				colors.add("#F7E98E");
				colors.add("#CCFF00");
				colors.add("#FF004F");
				colors.add("#228B22");
				colors.add("#A67B5B");
				colors.add("#0072BB");
				colors.add("#86608E");
				colors.add("#F64A8A");
				colors.add("#99C68E");
				colors.add("#FF00FF");
				colors.add("#FF77FF");
				colors.add("#E48400");
				colors.add("#DCDCDC");
				colors.add("#E49B0F");
				colors.add("#B06500");
				colors.add("#C9BE62");
				colors.add("#6082B6");
				colors.add("#E6E8FA");
				colors.add("#D4A017");
				colors.add("#EAC117");
				colors.add("#996515");
				colors.add("#FCC200");
				colors.add("#EDDA74");
				colors.add("#A8E4A0");
				colors.add("#5E5A80");
				colors.add("#DC381F");
				colors.add("#465945");
				colors.add("#B6B6B4");
				colors.add("#D1D0CE");
				colors.add("#504A4B");
				colors.add("#5E7D7E");
				colors.add("#4CC417");
				colors.add("#1164B4");
				colors.add("#6AA121");
				colors.add("#89C35C");
				colors.add("#ADFF2F");
				colors.add("#307D7E");
				colors.add("#808080");
				colors.add("#A99A86");
				colors.add("#00FF7F");
				colors.add("#E66C2C");
				colors.add("#446CCF");
				colors.add("#5218FA");
				colors.add("#E9D66B");
				colors.add("#3FFF00");
				colors.add("#C90016");
				colors.add("#EDE275");
				colors.add("#617C58");
				colors.add("#DF73FF");
				colors.add("#D462FF");
				colors.add("#F0FFF0");
				colors.add("#49796B");
				colors.add("#FF1DCE");
				colors.add("#F660AB");
				colors.add("#7FE817");
				colors.add("#355E3B");
				colors.add("#56A5EC");
				colors.add("#FCF75E");
				colors.add("#9CB071");
				colors.add("#B2EC5D");
				colors.add("#138808");
				colors.add("#E3A857");
				colors.add("#4B0082");
				colors.add("#002FA7");
				colors.add("#FF4F00");
				colors.add("#F4F0EC");
				colors.add("#009000");
				colors.add("#5EFB6E");
				colors.add("#F8DE7E");
				colors.add("#D73B3E");
				colors.add("#A50B5E");
				colors.add("#A0CFEC");
				colors.add("#46C7C7");
				colors.add("#FADA5E");
				colors.add("#BDDA57");
				colors.add("#29AB87");
				colors.add("#4CC552");
				colors.add("#C3B091");
				colors.add("#C5908E");
				colors.add("#E8000D");
				colors.add("#D6CADD");
				colors.add("#15317E");
				colors.add("#26619C");
				colors.add("#FEFE22");
				colors.add("#A9BA9D");
				colors.add("#CF1020");
				colors.add("#CCCCFF");
				colors.add("#C4C3D0");
				colors.add("#9457EB");
				colors.add("#FBAED2");
				colors.add("#EBDDE2");
				colors.add("#967BB6");
				colors.add("#FFF700");
				colors.add("#BFFF00");
				colors.add("#FFF44F");
				colors.add("#FDD5B1");
				colors.add("#ADDFFF");
				colors.add("#B5651D");
				colors.add("#E66771");
				colors.add("#E77471");
				colors.add("#F08080");
				colors.add("#93CCEA");
				colors.add("#F56991");
				colors.add("#E0FFFF");
				colors.add("#F984EF");
				colors.add("#FAFAD2");
				colors.add("#D3D3D3");
				colors.add("#F0E68C");
				colors.add("#B19CD9");
				colors.add("#FFB6C1");
				colors.add("#FFA07A");
				colors.add("#FF9999");
				colors.add("#3EA99F");
				colors.add("#CCFFFF");
				colors.add("#736AFF");
				colors.add("#778899");
				colors.add("#728FCE");
				colors.add("#B38B6D");
				colors.add("#E68FAC");
				colors.add("#C8A2C8");
				colors.add("#41A317");
				colors.add("#FAF0E6");
				colors.add("#C48793");
				colors.add("#534B4F");
				colors.add("#E41B17");
				colors.add("#7F38EC");
				colors.add("#E62020");
				colors.add("#FFBD88");
				colors.add("#FF00FF");
				colors.add("#F8F4FF");
				colors.add("#FBEC5D");
				colors.add("#6050DC");
				colors.add("#979AAA");
				colors.add("#FF8040");
				colors.add("#FF8243");
				colors.add("#74C365");
				colors.add("#566D7E");
				colors.add("#810541");
				colors.add("#43BFC7");
				colors.add("#E0B0FF");
				colors.add("#EF98AA");
				colors.add("#73C2FB");
				colors.add("#E5B73B");
				colors.add("#66DDAA");
				colors.add("#0000CD");
				colors.add("#F3E5AB");
				colors.add("#035096");
				colors.add("#347235");
				colors.add("#1C352D");
				colors.add("#DDA0DD");
				colors.add("#BA55D3");
				colors.add("#0067A5");
				colors.add("#9370DB");
				colors.add("#BB3385");
				colors.add("#3CB371");
				colors.add("#7B68EE");
				colors.add("#C9DC87");
				colors.add("#348017");
				colors.add("#674C47");
				colors.add("#0054B4");
				colors.add("#48D1CC");
				colors.add("#FDBCB4");
				colors.add("#BCC6CC");
				colors.add("#2B1B17");
				colors.add("#191970");
				colors.add("#004953");
				colors.add("#FFC40C");
				colors.add("#FEFCFF");
				colors.add("#F5FFFA");
				colors.add("#98FF98");
				colors.add("#646D7E");
				colors.add("#FBBBB9");
				colors.add("#827839");
				colors.add("#493D26");
				colors.add("#73A9C2");
				colors.add("#ADDFAD");
				colors.add("#30BA8F");
				colors.add("#997A8D");
				colors.add("#18453B");
				colors.add("#C54B8C");
				colors.add("#FFDB58");
				colors.add("#21421E");
				colors.add("#F6ADC6");
				colors.add("#FADA5E");
				colors.add("#59E817");
				colors.add("#FFA343");
				colors.add("#FE59C2");
				colors.add("#39FF14");
				colors.add("#F535AA");
				colors.add("#A4DDED");
				colors.add("#059033");
				colors.add("#78C7C7");
				colors.add("#806517");
				colors.add("#2B65EC");
				colors.add("#0077BE");
				colors.add("#CC7722");
				colors.add("#008000");
				colors.add("#3B3131");
				colors.add("#CFB53B");
				colors.add("#FDF5E6");
				colors.add("#796878");
				colors.add("#673147");
				colors.add("#C08081");
				colors.add("#808000");
				colors.add("#6B8E23");
				colors.add("#BAB86C");
				colors.add("#9AB973");
				colors.add("#0F0F0F");
				colors.add("#B784A7");
				colors.add("#FFA500");
				colors.add("#FF9F00");
				colors.add("#FF4500");
				colors.add("#F8D568");
				colors.add("#DA70D6");
				colors.add("#414A4C");
				colors.add("#FF6E4A");
				colors.add("#002147");
				colors.add("#1CA9C9");
				colors.add("#006600");
				colors.add("#273BE2");
				colors.add("#BCD4E6");
				colors.add("#CFECEC");
				colors.add("#987654");
				colors.add("#AF4035");
				colors.add("#9BC4E2");
				colors.add("#DDADAF");
				colors.add("#ABCDEF");
				colors.add("#E6BE8A");
				colors.add("#DCD0FF");
				colors.add("#F984E5");
				colors.add("#FADADD");
				colors.add("#96DED1");
				colors.add("#C9C0BB");
				colors.add("#ECEBBD");
				colors.add("#BC987E");
				colors.add("#78184A");
				colors.add("#E56717");
				colors.add("#50C878");
				colors.add("#B4CFEC");
				colors.add("#836953");
				colors.add("#CFCFC4");
				colors.add("#77DD77");
				colors.add("#F49AC2");
				colors.add("#FFB347");
				colors.add("#FFD1DC");
				colors.add("#B39EB5");
				colors.add("#FF6961");
				colors.add("#FDFD96");
				colors.add("#536878");
				colors.add("#FADFAD");
				colors.add("#EAE0C8");
				colors.add("#E6E200");
				colors.add("#1C39BB");
				colors.add("#32127A");
				colors.add("#D99058");
				colors.add("#F77FBE");
				colors.add("#701C1C");
				colors.add("#CC3333");
				colors.add("#FE28A2");
				colors.add("#000F89");
				colors.add("#123524");
				colors.add("#FDD7E4");
				colors.add("#FDDDE6");
				colors.add("#01796F");
				colors.add("#387C44");
				colors.add("#FAAFBE");
				colors.add("#E45E9D");
				colors.add("#E799A3");
				colors.add("#FC74FD");
				colors.add("#E4287C");
				colors.add("#E7ACCF");
				colors.add("#E7A1B0");
				colors.add("#F78FA7");
				colors.add("#93C572");
				colors.add("#9DC209");
				colors.add("#E5E4E2");
				colors.add("#B93B8F");
				colors.add("#7D0541");
				colors.add("#583759");
				colors.add("#7D0552");
				colors.add("#C6DEFF");
				colors.add("#FF8F00");
				colors.add("#003153");
				colors.add("#DF00FF");
				colors.add("#7F5A58");
				colors.add("#FF7518");
				colors.add("#F87217");
				colors.add("#800080");
				colors.add("#6C2DC7");
				colors.add("#B041FF");
				colors.add("#C38EC7");
				colors.add("#A74AC7");
				colors.add("#4E387E");
				colors.add("#69359C");
				colors.add("#571B7E");
				colors.add("#6A287E");
				colors.add("#9E7BFF");
				colors.add("#461B7E");
				colors.add("#9678B6");
				colors.add("#9D81BA");
				colors.add("#FE4EDA");
				colors.add("#7A5DC7");
				colors.add("#50404D");
				colors.add("#FF355E");
				colors.add("#E30B5D");
				colors.add("#915F6D");
				colors.add("#E25098");
				colors.add("#B3446C");
				colors.add("#D68A59");
				colors.add("#FF33CC");
				colors.add("#E3256B");
				colors.add("#FF0000");
				colors.add("#A52A2A");
				colors.add("#7F5217");
				colors.add("#FF5349");
				colors.add("#C71585");
				colors.add("#990012");
				colors.add("#004040");
				colors.add("#D70040");
				colors.add("#0892D0");
				colors.add("#B666D2");
				colors.add("#B03060");
				colors.add("#414833");
				colors.add("#1FCECB");
				colors.add("#C12869");
				colors.add("#E8ADAA");
				colors.add("#F9429E");
				colors.add("#674846");
				colors.add("#B76E79");
				colors.add("#E32636");
				colors.add("#FF66CC");
				colors.add("#AA98A9");
				colors.add("#905D5D");
				colors.add("#AB4E52");
				colors.add("#65000B");
				colors.add("#D40000");
				colors.add("#B38481");
				colors.add("#7F4E52");
				colors.add("#0038A8");
				colors.add("#2B60DE");
				colors.add("#CA2C92");
				colors.add("#FFD801");
				colors.add("#E0115F");
				colors.add("#F62217");
				colors.add("#FF0028");
				colors.add("#BB6528");
				colors.add("#E18E96");
				colors.add("#A81C07");
				colors.add("#80461B");
				colors.add("#C36241");
				colors.add("#00563F");
				colors.add("#8B4513");
				colors.add("#FF6700");
				colors.add("#FBB917");
				colors.add("#A1C935");
				colors.add("#FF8C69");
				colors.add("#FF91A4");
				colors.add("#C2B280");
				colors.add("#786D5F");
				colors.add("#ECD540");
				colors.add("#EE9A4D");
				colors.add("#967117");
				colors.add("#7E3817");
				colors.add("#507D2A");
				colors.add("#0F52BA");
				colors.add("#2554C7");
				colors.add("#CBA135");
				colors.add("#FF2400");
				colors.add("#76FF7A");
				colors.add("#C2DFFF");
				colors.add("#2E8B57");
				colors.add("#438D80");
				colors.add("#321414");
				colors.add("#437C17");
				colors.add("#CC6600");
				colors.add("#FFBA00");
				colors.add("#7F462C");
				colors.add("#8A795D");
				colors.add("#45CEA2");
				colors.add("#347C17");
				colors.add("#E55B3C");
				colors.add("#FC0FC0");
				colors.add("#8A4117");
				colors.add("#C0C0C0");
				colors.add("#CB410B");
				colors.add("#007474");
				colors.add("#6698FF");
				colors.add("#CF71AF");
				colors.add("#737CA1");
				colors.add("#708090");
				colors.add("#BCE954");
				colors.add("#726E6D");
				colors.add("#933D41");
				colors.add("#100C08");
				colors.add("#0FC0FC");
				colors.add("#A7FC00");
				colors.add("#4AA02C");
				colors.add("#4863A0");
				colors.add("#FADA5E");
				colors.add("#57E964");
				colors.add("#E4D96F");
				colors.add("#FFCC33");
				colors.add("#E67451");
				colors.add("#FAD6A5");
				colors.add("#FD5E53");
				colors.add("#ECE5B6");
				colors.add("#F94D00");
				colors.add("#F28500");
				colors.add("#FFCC00");
				colors.add("#483C32");
				colors.add("#8B8589");
				colors.add("#D0F0C0");
				colors.add("#F4C2C2");
				colors.add("#008080");
				colors.add("#367588");
				colors.add("#006D5B");
				colors.add("#E2725B");
				colors.add("#D8BFD8");
				colors.add("#DE6FA1");
				colors.add("#FC89AC");
				colors.add("#81D8D0");
				colors.add("#E08D3C");
				colors.add("#C88141");
				colors.add("#DBD7D2");
				colors.add("#FF6347");
				colors.add("#746CC0");
				colors.add("#FFC87C");
				colors.add("#7DFDFE");
				colors.add("#00755E");
				colors.add("#0073CF");
				colors.add("#417DC1");
				colors.add("#C25A7C");
				colors.add("#DEAA88");
				colors.add("#B57281");
				colors.add("#43C6DB");
				colors.add("#00FFEF");
				colors.add("#A0D6B4");
				colors.add("#66424D");
				colors.add("#8A496B");
				colors.add("#C45AEC");
				colors.add("#0033AA");
				colors.add("#D9004C");
				colors.add("#8878C3");
				colors.add("#536895");
				colors.add("#FFB300");
				colors.add("#3CD070");
				colors.add("#FF6FFF");
				colors.add("#120A8F");
				colors.add("#4166F5");
				colors.add("#635147");
				colors.add("#5B92E5");
				colors.add("#B78727");
				colors.add("#014421");
				colors.add("#7B1113");
				colors.add("#AE2029");
				colors.add("#E1AD21");
				colors.add("#D3003F");
				colors.add("#E55451");
				colors.add("#C5B358");
				colors.add("#7E354D");
				colors.add("#C80815");
				colors.add("#728C00");
				colors.add("#43B3AE");
				colors.add("#A020F0");
				colors.add("#7E587E");
				colors.add("#8D38C9");
				colors.add("#324AB2");
				colors.add("#F6358A");
				colors.add("#40826D");
				colors.add("#922724");
				colors.add("#9F1D35");
				colors.add("#DA1D81");
				colors.add("#FFA089");
				colors.add("#9F00FF");
				colors.add("#004242");
				colors.add("#EBF4FA");
				colors.add("#FC6C85");
				colors.add("#645452");				
				colors.add("#F5F5F5");
				colors.add("#A2ADD0");
				colors.add("#FF43A4");
				colors.add("#FC6C85");
				colors.add("#722F37");
				colors.add("#C6AEC7");
				colors.add("#C9A0DC");
				colors.add("#966F33");
				colors.add("#738678");
				colors.add("#0F4D92");
				colors.add("#52D017");
				colors.add("#FFAE42");
				colors.add("#0014A8");
				colors.add("#2C1608");
				colors.add("#54C571");
								
				final TextView LinkID = (TextView)findViewById(R.id.Linkid);
				final RelativeLayout RelLay = (RelativeLayout) findViewById(R.id.RelativeLayout);
				
				Random randomcolors = new Random();
				final int generatedRandomNum = randomcolors.nextInt(775);
				LinkID.setText(Integer.toString(generatedRandomNum));
				RelLay.setBackgroundColor(Color.parseColor(colors.get(generatedRandomNum)));
				colors.clear();
	}

	public int links() {
		
				links.add("http://devanswers.ru/a/Se");
				links.add("http://devanswers.ru/a/gb");
				links.add("http://devanswers.ru/a/1g");
				links.add("http://devanswers.ru/a/Rh");
				links.add("http://devanswers.ru/a/Dc");
				links.add("http://devanswers.ru/a/Id");
				links.add("http://devanswers.ru/a/Tb");
				links.add("http://devanswers.ru/a/yg");
				links.add("http://devanswers.ru/a/sj");
				links.add("http://devanswers.ru/a/pg");
				links.add("http://devanswers.ru/a/kh");
				links.add("http://devanswers.ru/a/rg");
				links.add("http://devanswers.ru/a/rf");
				links.add("http://devanswers.ru/a/Bd");
				links.add("http://devanswers.ru/a/1j");
				links.add("http://devanswers.ru/a/Li");
				links.add("http://devanswers.ru/a/bd");
				links.add("http://devanswers.ru/a/Xi");
				links.add("http://devanswers.ru/a/2j");
				links.add("http://devanswers.ru/a/6f");
				links.add("http://devanswers.ru/a/Eb");
				links.add("http://devanswers.ru/a/Lg");
				links.add("http://devanswers.ru/a/4b");
				links.add("http://devanswers.ru/a/gf");
				links.add("http://devanswers.ru/a/zb");
				links.add("http://devanswers.ru/a/Hb");
				links.add("http://devanswers.ru/a/jh");
				links.add("http://devanswers.ru/a/Ah");
				links.add("http://devanswers.ru/a/wh");
				links.add("http://devanswers.ru/a/Lc");
				links.add("http://devanswers.ru/a/xe");
				links.add("http://devanswers.ru/a/Hi");
				links.add("http://devanswers.ru/a/Fh");
				links.add("http://devanswers.ru/a/Ic");
				links.add("http://devanswers.ru/a/ii");
				links.add("http://devanswers.ru/a/Wb");
				links.add("http://devanswers.ru/a/Ad");
				links.add("http://devanswers.ru/a/kc");
				links.add("http://devanswers.ru/a/Rd");
				links.add("http://devanswers.ru/a/Zc");
				links.add("http://devanswers.ru/a/Wi");
				links.add("http://devanswers.ru/a/Bg");
				links.add("http://devanswers.ru/a/ge");
				links.add("http://devanswers.ru/a/zj");
				links.add("http://devanswers.ru/a/pe");
				links.add("http://devanswers.ru/a/Ji");
				links.add("http://devanswers.ru/a/Bh");
				links.add("http://devanswers.ru/a/Kc");
				links.add("http://devanswers.ru/a/qj");
				links.add("http://devanswers.ru/a/xd");
				links.add("http://devanswers.ru/a/ub");
				links.add("http://devanswers.ru/a/Ee");
				links.add("http://devanswers.ru/a/gd");
				links.add("http://devanswers.ru/a/rc");
				links.add("http://devanswers.ru/a/Cb");
				links.add("http://devanswers.ru/a/fh");
				links.add("http://devanswers.ru/a/lf");
				links.add("http://devanswers.ru/a/0b");
				links.add("http://devanswers.ru/a/gg");
				links.add("http://devanswers.ru/a/Wg");
				links.add("http://devanswers.ru/a/yf");
				links.add("http://devanswers.ru/a/0h");
				links.add("http://devanswers.ru/a/Bi");
				links.add("http://devanswers.ru/a/li");
				links.add("http://devanswers.ru/a/ei");
				links.add("http://devanswers.ru/a/bj");
				links.add("http://devanswers.ru/a/hj");
				links.add("http://devanswers.ru/a/ki");
				links.add("http://devanswers.ru/a/Gf");
				links.add("http://devanswers.ru/a/tg");
				links.add("http://devanswers.ru/a/Sg");
				links.add("http://devanswers.ru/a/nd");
				links.add("http://devanswers.ru/a/1f");
				links.add("http://devanswers.ru/a/He");
				links.add("http://devanswers.ru/a/Ib");
				links.add("http://devanswers.ru/a/re");
				links.add("http://devanswers.ru/a/ah");
				links.add("http://devanswers.ru/a/Td");
				links.add("http://devanswers.ru/a/sc");
				links.add("http://devanswers.ru/a/7f");
				links.add("http://devanswers.ru/a/Rf");
				links.add("http://devanswers.ru/a/Jh");
				links.add("http://devanswers.ru/a/Vd");
				links.add("http://devanswers.ru/a/tc");
				links.add("http://devanswers.ru/a/Fi");
				links.add("http://devanswers.ru/a/ee");
				links.add("http://devanswers.ru/a/he");
				links.add("http://devanswers.ru/a/uf");
				links.add("http://devanswers.ru/a/Hd");
				links.add("http://devanswers.ru/a/9b");
				links.add("http://devanswers.ru/a/hg");
				links.add("http://devanswers.ru/a/eb");
				links.add("http://devanswers.ru/a/oc");
				links.add("http://devanswers.ru/a/Ed");
				links.add("http://devanswers.ru/a/0c");
				links.add("http://devanswers.ru/a/ce");
				links.add("http://devanswers.ru/a/ej");
				links.add("http://devanswers.ru/a/Hg");
				links.add("http://devanswers.ru/a/Jd");
				links.add("http://devanswers.ru/a/cg");
				links.add("http://devanswers.ru/a/xb");
				links.add("http://devanswers.ru/a/Pd");
				links.add("http://devanswers.ru/a/Jf");
				links.add("http://devanswers.ru/a/Je");
				links.add("http://devanswers.ru/a/5h");
				links.add("http://devanswers.ru/a/wi");
				links.add("http://devanswers.ru/a/Nf");
				links.add("http://devanswers.ru/a/Xg");
				links.add("http://devanswers.ru/a/sb");
				links.add("http://devanswers.ru/a/fi");
				links.add("http://devanswers.ru/a/0d");
				links.add("http://devanswers.ru/a/de");
				links.add("http://devanswers.ru/a/Ki");
				links.add("http://devanswers.ru/a/5e");
				links.add("http://devanswers.ru/a/Wc");
				links.add("http://devanswers.ru/a/2d");
				links.add("http://devanswers.ru/a/Fd");
				links.add("http://devanswers.ru/a/md");
				links.add("http://devanswers.ru/a/jc");
				links.add("http://devanswers.ru/a/4c");
				links.add("http://devanswers.ru/a/Zf");
				links.add("http://devanswers.ru/a/tb");
				links.add("http://devanswers.ru/a/wj");
				links.add("http://devanswers.ru/a/kj");
				links.add("http://devanswers.ru/a/De");
				links.add("http://devanswers.ru/a/mi");
				links.add("http://devanswers.ru/a/4e");
				links.add("http://devanswers.ru/a/Md");
				links.add("http://devanswers.ru/a/gj");
				links.add("http://devanswers.ru/a/mh");
				links.add("http://devanswers.ru/a/2g");
				links.add("http://devanswers.ru/a/sf");
				links.add("http://devanswers.ru/a/Db");
				links.add("http://devanswers.ru/a/4d");
				links.add("http://devanswers.ru/a/zi");
				links.add("http://devanswers.ru/a/oe");
				links.add("http://devanswers.ru/a/zh");
				links.add("http://devanswers.ru/a/Hh");
				links.add("http://devanswers.ru/a/Ph");
				links.add("http://devanswers.ru/a/2i");
				links.add("http://devanswers.ru/a/Ug");
				links.add("http://devanswers.ru/a/0i");
				links.add("http://devanswers.ru/a/Ec");
				links.add("http://devanswers.ru/a/fd");
				links.add("http://devanswers.ru/a/sh");
				links.add("http://devanswers.ru/a/bb");
				links.add("http://devanswers.ru/a/Ne");
				links.add("http://devanswers.ru/a/di");
				links.add("http://devanswers.ru/a/Me");
				links.add("http://devanswers.ru/a/Oh");
				links.add("http://devanswers.ru/a/le");
				links.add("http://devanswers.ru/a/Qh");
				links.add("http://devanswers.ru/a/Fb");
				links.add("http://devanswers.ru/a/kb");
				links.add("http://devanswers.ru/a/Mc");
				links.add("http://devanswers.ru/a/Pe");
				links.add("http://devanswers.ru/a/ec");
				links.add("http://devanswers.ru/a/id");
				links.add("http://devanswers.ru/a/Le");
				links.add("http://devanswers.ru/a/Qf");
				links.add("http://devanswers.ru/a/cb");
				links.add("http://devanswers.ru/a/lg");
				links.add("http://devanswers.ru/a/rd");
				links.add("http://devanswers.ru/a/lj");
				links.add("http://devanswers.ru/a/Cf");
				links.add("http://devanswers.ru/a/td");
				links.add("http://devanswers.ru/a/5g");
				links.add("http://devanswers.ru/a/qh");
				links.add("http://devanswers.ru/a/2f");
				links.add("http://devanswers.ru/a/jj");
				links.add("http://devanswers.ru/a/fj");
				links.add("http://devanswers.ru/a/Xf");
				links.add("http://devanswers.ru/a/ff");
				links.add("http://devanswers.ru/a/ph");
				links.add("http://devanswers.ru/a/Od");
				links.add("http://devanswers.ru/a/fe");
				links.add("http://devanswers.ru/a/Zh");
				links.add("http://devanswers.ru/a/Kf");
				links.add("http://devanswers.ru/a/jg");
				links.add("http://devanswers.ru/a/Og");
				links.add("http://devanswers.ru/a/Ab");
				links.add("http://devanswers.ru/a/yj");
				links.add("http://devanswers.ru/a/te");
				links.add("http://devanswers.ru/a/6i");
				links.add("http://devanswers.ru/a/Ui");
				links.add("http://devanswers.ru/a/rb");
				links.add("http://devanswers.ru/a/vf");
				links.add("http://devanswers.ru/a/je");
				links.add("http://devanswers.ru/a/Oc");
				links.add("http://devanswers.ru/a/8e");
				links.add("http://devanswers.ru/a/Zd");
				links.add("http://devanswers.ru/a/Rg");
				links.add("http://devanswers.ru/a/eg");
				links.add("http://devanswers.ru/a/Gg");
				links.add("http://devanswers.ru/a/ie");
				links.add("http://devanswers.ru/a/nj");
				links.add("http://devanswers.ru/a/Af");
				links.add("http://devanswers.ru/a/ve");
				links.add("http://devanswers.ru/a/Mb");
				links.add("http://devanswers.ru/a/mj");
				links.add("http://devanswers.ru/a/Dd");
				links.add("http://devanswers.ru/a/ug");
				links.add("http://devanswers.ru/a/Gi");
				links.add("http://devanswers.ru/a/ri");
				links.add("http://devanswers.ru/a/Qe");
				links.add("http://devanswers.ru/a/Ni");
				links.add("http://devanswers.ru/a/xh");
				links.add("http://devanswers.ru/a/6h");
				links.add("http://devanswers.ru/a/zc");
				links.add("http://devanswers.ru/a/Nd");
				links.add("http://devanswers.ru/a/Gb");
				links.add("http://devanswers.ru/a/Of");
				links.add("http://devanswers.ru/a/Ih");
				links.add("http://devanswers.ru/a/Lh");
				links.add("http://devanswers.ru/a/Ri");
				links.add("http://devanswers.ru/a/dc");
				links.add("http://devanswers.ru/a/Gd");
				links.add("http://devanswers.ru/a/we");
				links.add("http://devanswers.ru/a/pf");
				links.add("http://devanswers.ru/a/zf");
				links.add("http://devanswers.ru/a/ad");
				links.add("http://devanswers.ru/a/Mf");
				links.add("http://devanswers.ru/a/Xd");
				links.add("http://devanswers.ru/a/ue");
				links.add("http://devanswers.ru/a/pi");
				links.add("http://devanswers.ru/a/Sc");
				links.add("http://devanswers.ru/a/8d");
				links.add("http://devanswers.ru/a/db");
				links.add("http://devanswers.ru/a/xj");
				links.add("http://devanswers.ru/a/Yd");
				links.add("http://devanswers.ru/a/Ye");
				links.add("http://devanswers.ru/a/Uf");
				links.add("http://devanswers.ru/a/3e");
				links.add("http://devanswers.ru/a/sd");
				links.add("http://devanswers.ru/a/tf");
				links.add("http://devanswers.ru/a/Ng");
				links.add("http://devanswers.ru/a/Rc");
				links.add("http://devanswers.ru/a/dj");
				links.add("http://devanswers.ru/a/Gc");
				links.add("http://devanswers.ru/a/nf");
				links.add("http://devanswers.ru/a/Mi");
				links.add("http://devanswers.ru/a/bc");
				links.add("http://devanswers.ru/a/4g");
				links.add("http://devanswers.ru/a/7d");
				links.add("http://devanswers.ru/a/bh");
				links.add("http://devanswers.ru/a/Tc");
				links.add("http://devanswers.ru/a/gc");
				links.add("http://devanswers.ru/a/7b");
				links.add("http://devanswers.ru/a/2c");
				links.add("http://devanswers.ru/a/hc");
				links.add("http://devanswers.ru/a/ui");
				links.add("http://devanswers.ru/a/Ue");
				links.add("http://devanswers.ru/a/Mh");
				links.add("http://devanswers.ru/a/gh");
				links.add("http://devanswers.ru/a/ef");
				links.add("http://devanswers.ru/a/Hf");
				links.add("http://devanswers.ru/a/hi");
				links.add("http://devanswers.ru/a/Wf");
				links.add("http://devanswers.ru/a/Wh");
				links.add("http://devanswers.ru/a/1c");
				links.add("http://devanswers.ru/a/ch");
				links.add("http://devanswers.ru/a/qi");
				links.add("http://devanswers.ru/a/pd");
				links.add("http://devanswers.ru/a/Sb");
				links.add("http://devanswers.ru/a/Xh");
				links.add("http://devanswers.ru/a/mg");
				links.add("http://devanswers.ru/a/Qi");
				links.add("http://devanswers.ru/a/pj");
				links.add("http://devanswers.ru/a/Te");
				links.add("http://devanswers.ru/a/ng");
				links.add("http://devanswers.ru/a/vh");
				links.add("http://devanswers.ru/a/cj");
				links.add("http://devanswers.ru/a/yb");
				links.add("http://devanswers.ru/a/Ce");
				links.add("http://devanswers.ru/a/7g");
				links.add("http://devanswers.ru/a/Re");
				links.add("http://devanswers.ru/a/Of");
				links.add("http://devanswers.ru/a/pi");
				links.add("http://devanswers.ru/a/db");
				links.add("http://devanswers.ru/a/nf");
				links.add("http://devanswers.ru/a/ef");
				links.add("http://devanswers.ru/a/Te");
				links.add("http://devanswers.ru/a/vh");
				links.add("http://devanswers.ru/a/ld");
				links.add("http://devanswers.ru/a/yb");
				links.add("http://devanswers.ru/a/Xc");
				links.add("http://devanswers.ru/a/xg");
				links.add("http://devanswers.ru/a/Ce");
				links.add("http://devanswers.ru/a/tj");
				links.add("http://devanswers.ru/a/Ke");
				links.add("http://devanswers.ru/a/Re");
				links.add("http://devanswers.ru/a/wb");
				links.add("http://devanswers.ru/a/Be");
				links.add("http://devanswers.ru/a/3f");
				links.add("http://devanswers.ru/a/3d");
				links.add("http://devanswers.ru/a/Lf");
				links.add("http://devanswers.ru/a/Ge");
				links.add("http://devanswers.ru/a/wc");
				links.add("http://devanswers.ru/a/jd");
				links.add("http://devanswers.ru/a/Ai");
				links.add("http://devanswers.ru/a/ne");
				links.add("http://devanswers.ru/a/Pc");
				links.add("http://devanswers.ru/a/gi");
				links.add("http://devanswers.ru/a/qg");
				links.add("http://devanswers.ru/a/kd");
				links.add("http://devanswers.ru/a/Bf");
				links.add("http://devanswers.ru/a/Dh");
				links.add("http://devanswers.ru/a/ig");
				links.add("http://devanswers.ru/a/8f");
				links.add("http://devanswers.ru/a/Ob");
				links.add("http://devanswers.ru/a/cf");
				links.add("http://devanswers.ru/a/Ch");
				links.add("http://devanswers.ru/a/Uc");
				links.add("http://devanswers.ru/a/Sf");
				links.add("http://devanswers.ru/a/Kg");
				links.add("http://devanswers.ru/a/Fc");
				links.add("http://devanswers.ru/a/yc");
				links.add("http://devanswers.ru/a/Cg");
				links.add("http://devanswers.ru/a/9i");
				links.add("http://devanswers.ru/a/lb");
				links.add("http://devanswers.ru/a/Rb");
				links.add("http://devanswers.ru/a/df");
				links.add("http://devanswers.ru/a/Sh");
				links.add("http://devanswers.ru/a/Pb");
				links.add("http://devanswers.ru/a/Qg");
				links.add("http://devanswers.ru/a/5c");
				links.add("http://devanswers.ru/a/8b");
				links.add("http://devanswers.ru/a/6b");
				links.add("http://devanswers.ru/a/nb");
				links.add("http://devanswers.ru/a/og");
				links.add("http://devanswers.ru/a/Si");
				links.add("http://devanswers.ru/a/hd");
				links.add("http://devanswers.ru/a/5b");
				links.add("http://devanswers.ru/a/af");
				links.add("http://devanswers.ru/a/wf");
				links.add("http://devanswers.ru/a/fc");
				links.add("http://devanswers.ru/a/zg");
				links.add("http://devanswers.ru/a/8c");
				links.add("http://devanswers.ru/a/qb");
				links.add("http://devanswers.ru/a/vg");
				links.add("http://devanswers.ru/a/Ac");
				links.add("http://devanswers.ru/a/8h");
				links.add("http://devanswers.ru/a/bg");
				links.add("http://devanswers.ru/a/3i");
				links.add("http://devanswers.ru/a/Cd");
				links.add("http://devanswers.ru/a/Ib");
				links.add("http://devanswers.ru/a/be");
				links.add("http://devanswers.ru/a/Tf");
				links.add("http://devanswers.ru/a/1b");
				links.add("http://devanswers.ru/a/Ud");
				links.add("http://devanswers.ru/a/xf");
				links.add("http://devanswers.ru/a/ib");
				links.add("http://devanswers.ru/a/ye");
				links.add("http://devanswers.ru/a/wg");
				links.add("http://devanswers.ru/a/Th");
				links.add("http://devanswers.ru/a/9h");
				links.add("http://devanswers.ru/a/nh");
				links.add("http://devanswers.ru/a/uh");
				links.add("http://devanswers.ru/a/Ei");
				links.add("http://devanswers.ru/a/Eg");
				links.add("http://devanswers.ru/a/qc");
				links.add("http://devanswers.ru/a/vb");
				links.add("http://devanswers.ru/a/Vc");
				links.add("http://devanswers.ru/a/hh");
				links.add("http://devanswers.ru/a/vc");
				links.add("http://devanswers.ru/a/4h");
				links.add("http://devanswers.ru/a/zd");
				links.add("http://devanswers.ru/a/Vg");
				links.add("http://devanswers.ru/a/0e");
				links.add("http://devanswers.ru/a/ae");
				links.add("http://devanswers.ru/a/If");
				links.add("http://devanswers.ru/a/Ie");
				links.add("http://devanswers.ru/a/qf");
				links.add("http://devanswers.ru/a/Yf");
				links.add("http://devanswers.ru/a/pb");
				links.add("http://devanswers.ru/a/ci");
				links.add("http://devanswers.ru/a/Yc");
				links.add("http://devanswers.ru/a/dh");
				links.add("http://devanswers.ru/a/ij");
				links.add("http://devanswers.ru/a/Kb");
				links.add("http://devanswers.ru/a/ag");
				links.add("http://devanswers.ru/a/rj");
				links.add("http://devanswers.ru/a/ze");
				links.add("http://devanswers.ru/a/Ig");
				links.add("http://devanswers.ru/a/0j");
				links.add("http://devanswers.ru/a/Qc");
				links.add("http://devanswers.ru/a/5f");
				links.add("http://devanswers.ru/a/vi");
				links.add("http://devanswers.ru/a/kg");
				links.add("http://devanswers.ru/a/Lb");
				links.add("http://devanswers.ru/a/rh");
				links.add("http://devanswers.ru/a/fg");
				links.add("http://devanswers.ru/a/5i");
				links.add("http://devanswers.ru/a/bf");
				links.add("http://devanswers.ru/a/bi");
				links.add("http://devanswers.ru/a/Ii");
				links.add("http://devanswers.ru/a/Vi");
				links.add("http://devanswers.ru/a/2h");
				links.add("http://devanswers.ru/a/4f");
				links.add("http://devanswers.ru/a/We");
				links.add("http://devanswers.ru/a/Bb");
				links.add("http://devanswers.ru/a/mf");
				links.add("http://devanswers.ru/a/Eh");
				links.add("http://devanswers.ru/a/9g");
				links.add("http://devanswers.ru/a/Bc");
				links.add("http://devanswers.ru/a/Qd");
				links.add("http://devanswers.ru/a/Ti");
				links.add("http://devanswers.ru/a/Dg");
				links.add("http://devanswers.ru/a/Qb");
				links.add("http://devanswers.ru/a/1e");
				links.add("http://devanswers.ru/a/ai");
				links.add("http://devanswers.ru/a/lc");
				links.add("http://devanswers.ru/a/7h");
				links.add("http://devanswers.ru/a/uj");
				links.add("http://devanswers.ru/a/hf");
				links.add("http://devanswers.ru/a/3h");
				links.add("http://devanswers.ru/a/Nb");
				links.add("http://devanswers.ru/a/5d");
				links.add("http://devanswers.ru/a/Ae");
				links.add("http://devanswers.ru/a/xi");
				links.add("http://devanswers.ru/a/Ld");
				links.add("http://devanswers.ru/a/Jc");
				links.add("http://devanswers.ru/a/Vf");
				links.add("http://devanswers.ru/a/od");
				links.add("http://devanswers.ru/a/Mg");
				links.add("http://devanswers.ru/a/8i");
				links.add("http://devanswers.ru/a/Pf");
				links.add("http://devanswers.ru/a/nc");
				links.add("http://devanswers.ru/a/Yi");
				links.add("http://devanswers.ru/a/mc");
				links.add("http://devanswers.ru/a/Oe");
				links.add("http://devanswers.ru/a/Yb");
				links.add("http://devanswers.ru/a/th");
				links.add("http://devanswers.ru/a/me");
				links.add("http://devanswers.ru/a/oi");
				links.add("http://devanswers.ru/a/Uh");
				links.add("http://devanswers.ru/a/jf");
				links.add("http://devanswers.ru/a/dg");
				links.add("http://devanswers.ru/a/sg");
				links.add("http://devanswers.ru/a/xc");
				
				Random rand = new Random();
				number = rand.nextInt(440);
				return(number);
		
	}
	
	public boolean isOnline() {
		String cs = Context.CONNECTIVITY_SERVICE;
		ConnectivityManager cm = (ConnectivityManager) getSystemService(cs);
		if (cm.getActiveNetworkInfo() == null) {

			return false;
		}
		return cm.getActiveNetworkInfo().isConnectedOrConnecting();
	}
	
	public boolean onOptionsItemSelected(MenuItem item) {
				
		switch (item.getItemId()) {
		case R.id.i_about:
			AlertDialog();
			return true;
		case R.id.i_share:	{
			
			ShareActionProvider mShareActionProvider = (ShareActionProvider) shareItem.getActionProvider();
					
			Intent shareIntent = new Intent(Intent.ACTION_SEND);
			shareIntent.setAction(Intent.ACTION_SEND);
			shareIntent.setType("text/plain");
			shareIntent.putExtra(Intent.EXTRA_TEXT, "Девелопер ответил: " + note + "." +
					" Оригинальная цитата доступна здесь: " + links.get(number));
					
			mShareActionProvider.setShareIntent(shareIntent);
			
			return true;	
		}
			
		default:
			return super.onOptionsItemSelected(item);
		}
		
	}
	
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		getMenuInflater().inflate(R.menu.main, menu);
		
		shareItem = (MenuItem) menu.findItem(R.id.i_share);
		
		return true;
	}
	
	public boolean AlertDialog() {
	AlertDialog.Builder builder = new AlertDialog.Builder(this);
	builder.setTitle("О приложении DevAnswers").setMessage("Автор приложения - Taurusha." +
			" Оригинальные цитаты достуны на сайте devanswers.ru." +
			" Все права на используемый материал принадлежат его владельцу. ")
	                        .setCancelable(false)
	        .setPositiveButton("Ok", new DialogInterface.OnClickListener() {
	            public void onClick(DialogInterface dialog, int id) {
	                // do something if OK
	            }
	        });
	builder.create().show();
	return false;
	}
	
	class MyTask extends AsyncTask<Void, Void, Void> {

		@Override
		protected void onPreExecute() {
			super.onPreExecute();			
			
			ProgressDialog = new ProgressDialog(MainActivity.this);
			ProgressDialog.setMessage("Загрузка...");
			ProgressDialog.setIndeterminate(true);
			ProgressDialog.setCancelable(false);
			ProgressDialog.show();	
			
	}

		@Override
		protected Void doInBackground(Void... params) {
								
			try {				
				
				links();				
				Document doc = null;
	            doc = Jsoup.connect((String) links.get(number)).get();
	            element = doc.select("h1 > a > span");
	            note = element.tagName("span").text(); 
	            
				
	        } catch (IOException e) {
	            e.printStackTrace();
	        }
			
			return null;
				
		}

		@Override
		protected void onPostExecute(Void result) {
			super.onPostExecute(result);
			
			if (parsingSuccessful == true){
	            if (ProgressDialog.isShowing()){
	            	ProgressDialog.dismiss();
	            }
			}
			
			NodeText.setText(note);
			colors();
			
		}
	}

}

